# Generated by Django 4.2 on 2023-05-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='C:/Users/User/Documents/ES _PD_BRAC_2302/media/defult/profile.jpg', null=True, upload_to='Profile/'),
        ),
    ]
