# Generated by Django 4.2 on 2023-05-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='defult/profile.jpg', null=True, upload_to='Profile/'),
        ),
    ]
